# Generated by Django 3.2.4 on 2021-06-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=50)),
                ('kadastr_number', models.CharField(max_length=20)),
                ('kadastr_sum', models.CharField(max_length=20)),
                ('economic_num', models.CharField(max_length=20)),
                ('floor', models.CharField(max_length=2)),
                ('total_area', models.CharField(max_length=50)),
                ('house_area', models.CharField(max_length=50)),
                ('living_room', models.FileField(max_length=50, upload_to='')),
                ('extra_info', models.CharField(max_length=50)),
                ('property_type', models.CharField(max_length=50)),
                ('register_number', models.CharField(max_length=50)),
                ('register_date', models.CharField(max_length=12)),
                ('foundation_documents', models.FileField(upload_to='')),
                ('kadastr_copy', models.FileField(upload_to='files/')),
                ('kadastr_contract_number', models.CharField(max_length=50)),
                ('kadastr_contract_date', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='User_housemate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='avatars/')),
                ('birth_date', models.CharField(max_length=12)),
                ('sex', models.CharField(max_length=10)),
                ('passport_data', models.CharField(max_length=9)),
                ('inn', models.CharField(max_length=10)),
                ('home_tel', models.CharField(default=None, max_length=13, null=True)),
                ('family', models.CharField(max_length=10)),
                ('actual_address', models.CharField(default=None, max_length=50)),
                ('registration_address', models.CharField(max_length=50)),
                ('work_info', models.CharField(max_length=50)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('law_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User_tel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_tel', models.CharField(max_length=13)),
                ('User_tel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='User_law_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_num', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=12)),
                ('User_law_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='User_housemate_tel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_tel', models.CharField(max_length=13)),
                ('User_housemate_tel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_housemate')),
            ],
        ),
        migrations.AddField(
            model_name='user_housemate',
            name='User_housemate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_info'),
        ),
        migrations.CreateModel(
            name='Tex_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_date', models.CharField(max_length=12)),
                ('floor_count', models.CharField(max_length=50)),
                ('wall_material', models.CharField(max_length=50)),
                ('electricity', models.BooleanField()),
                ('gas', models.BooleanField()),
                ('water', models.BooleanField()),
                ('heating', models.BooleanField()),
                ('water_2', models.BooleanField()),
                ('communication', models.BooleanField()),
                ('lift', models.BooleanField()),
                ('Tex_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.property_info')),
            ],
        ),
        migrations.CreateModel(
            name='Room_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('room_area', models.CharField(max_length=50)),
                ('Room_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.property_info')),
            ],
        ),
        migrations.CreateModel(
            name='Property_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='property_photos/')),
                ('Property_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.property_info')),
            ],
        ),
        migrations.AddField(
            model_name='property_info',
            name='Property_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_info'),
        ),
        migrations.CreateModel(
            name='Planting_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('count', models.CharField(max_length=50)),
                ('Planting_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.garden_info')),
            ],
        ),
        migrations.CreateModel(
            name='Plant_type_fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('Plant_type_fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.garden_info')),
            ],
        ),
        migrations.CreateModel(
            name='Plant_type_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('Plant_type_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.garden_info')),
            ],
        ),
        migrations.AddField(
            model_name='garden_info',
            name='Garden_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_info'),
        ),
        migrations.CreateModel(
            name='Education_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=12)),
                ('finish_date', models.CharField(max_length=12)),
                ('education_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_info')),
            ],
        ),
    ]
