# Generated by Django 3.2.4 on 2021-06-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_info',
            name='living_room',
            field=models.CharField(max_length=50),
        ),
    ]
